#!/bin/bash

if [ -f "/etc/bitworker/mysql-dump.sh" ]; then
    /etc/bitworker/mysql-dump.sh >> /dev/null 2>&1
fi

if [ -f "/etc/bitworker/rsync/copyjob.sh" ]; then
    /etc/bitworker/rsync/copyjob.sh
fi

exit 0
