#!/bin/bash

### https://stackoverflow.com/questions/969407/determining-age-of-a-file-in-shell-script
###
###

### vars
###
###
folder=/etc/letsencrypt/live
file=/etc/letsencrypt/live/www.bitw0rker.de/privkey.pem




### Check for Cert renew
###
###
certbot renew


if [ -f "/etc/systemd/system/multi-user.target.wants/httpd.service" ]; then
    
    if [ "$(find $folder -mmin -5)" != "" ]; then
        systemctl reload httpd
    fi

fi


if [ -f "/etc/systemd/system/multi-user.target.wants/chatO.service" ]; then

    if [ "$(find $file -mmin -5)" == "" ]; then
        systemctl restart chatO
    fi

fi


exit 0